### ISSUE TITLE
Noise on output

### ISSUE THREAD

**Issue by AIisCool** [yangxy/PASD#16]
Usually on darker areas, there is some noise like this:
![pasd-noise](https://github.com/yangxy/PASD/assets/92149242/164a09c2-ab8e-4d15-b16d-c7d183ed85cf)

Is there a way to reduce that noise? Or add something to the code to denoise it? Thank you🙏

**Comment by yangxy** [comment]
PASD always tends to generate details. I am working on it to reduce the artifacts.

**Comment by AIisCool** [comment]
@yangxy Ok, thank you for your continued work on this! Very amazing!

**Comment by MasahideOkada** [comment]
Can [zero terminal SNR](https://arxiv.org/abs/2305.08891) solve this issue?

**Comment by yangxy** [comment]
> Can [zero terminal SNR](https://arxiv.org/abs/2305.08891) solve this issue?

Thanks for your advice. I have tried the offset noise trick (similar to the zero terminal SNR) and it seems it can partly solved the issue.  The code is updated. Please have a try now.

**Comment by yangxy** [comment]
> Usually on darker areas, there is some noise like this: ![pasd-noise](https://user-images.githubusercontent.com/92149242/273988916-164a09c2-ab8e-4d15-b16d-c7d183ed85cf.png)
> 
> Is there a way to reduce that noise? Or add something to the code to denoise it? Thank you🙏

Hi, there. I have solved this issue by initializing the latents with LR images. And the SR results also become much more stable. The source codes have been updated.
