### ISSUE TITLE
Data load error, configuration file not found

### ISSUE THREAD

**Issue by sacred178953** [yangxy/PASD#26]
Dear authors,
I have read about your PASD work,however, when I used the DIV2K dataset for training, I could not find the configuration file params_realesrgan.yml, and after checking, I found that there was no problem with the file name and path.
![1](https://github.com/yangxy/PASD/assets/108571380/b7e41ee3-1a44-4e90-a897-d82537bae24a)

**Comment by chky** [comment]
same error，have you got the params_realsrgan.yml ？

**Comment by Anguliachao** [comment]
I think it's only becoz the problem of initializing opt_path in `def __init__` arguments section, it cannot concatenate the path, put ur 
`opt_path=os.path.join(...)` in the mainbody of init function will do

**Comment by sacred178953** [comment]
> 同样的错误，你有params_realsrgan.yml吗？

**Comment by yangxy** [comment]
My fault. I will update the code very soon.
