### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [yangxy/PASD#30]
Hi,
Thanks so much for making this amazing model! Would you consider making it open source by adding a OSI-approved license (ie MIT/Apache 2.0/ISC)?
Thank you!

**Comment by yangxy** [comment]
Will update soon.

**Comment by fakerybakery** [comment]
Thanks!

**Comment by yangxy** [comment]
done

**Comment by fakerybakery** [comment]
Thanks! But the disclaimer still says:

> © Alibaba, 2023. For academic and non-commercial use only.

**Comment by fakerybakery** [comment]
Might it be possible to remove this or add clarification?
Thanks!

**Comment by yangxy** [comment]
> Might it be possible to remove this or add clarification? Thanks!

Removed.
