### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by sacred178953** [yangxy/PASD#31]
Dear authors,
I have read about your PASD work,and I used the DIV2K dataset for training,due to the limitation of GPU (48GB of graphics memory), I reduced the epochs, batch size, and steps, but the training progress bar did not move, and in the end, the model weights were saved.
![1](https://github.com/yangxy/PASD/assets/108571380/4f23ea24-a8cc-4ab6-92c4-386bbc324012)

**Comment by sunzhe09** [comment]
你好，你的数据集可以共享一下吗？作者提供的链接没法访问

**Comment by sacred178953** [comment]
> 你好，你的数据集可以共享一下吗？作者提供的链接没法访问

我数据集在服务器上，没法共享啊

**Comment by sacred178953** [comment]
> 你好，你的数据集可以共享一下吗？作者提供的链接没法访问

直接在浏览器网址复制搜索http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip，就可以下载数据集了，但是没有标签文件，所以还是训练不了，我现在就卡在这最后一步

**Comment by yangxy** [comment]
> Dear authors, I have read about your PASD work,and I used the DIV2K dataset for training,due to the limitation of GPU (48GB of graphics memory), I reduced the epochs, batch size, and steps, but the training progress bar did not move, and in the end, the model weights were saved. ![1](https://private-user-images.githubusercontent.com/108571380/296719012-4f23ea24-a8cc-4ab6-92c4-386bbc324012.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzAzMTcsIm5iZiI6MTcxMDczMDAxNywicGF0aCI6Ii8xMDg1NzEzODAvMjk2NzE5MDEyLTRmMjNlYTI0LWE4Y2MtNGFiNi05MmM0LTM4NmJiYzMyNDAxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMjQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2M4YTlkMTJmMGNiZDkzNmNkOGQyYTYyMTc4NmJjYzBmZTdmMzY3NzRkMzk2YmIxY2JkMmI3ZDEyNGRkMzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9pQe0-feXK7EF8_lgK90vUNvWQOOhKb6fh2n7G8hwVM)

It seems like the progress bar did not updated properly.

**Comment by ZH3nGsQ** [comment]
请问如何生成DIV2K训练集的标签文件呢？

**Comment by chiixy** [comment]
I met the same problem, the training progress bar did not move, and just complete the training and save ckpt.  I find it's just make mistake in the data_path: need to check 56 line if glob your data correctly.

![Image](https://github.com/user-attachments/assets/dfc1034f-6dd4-495c-9cbd-5987b871541c)
