### ISSUE TITLE
你好，怎么生成训练的标签？可以指导一下吗

### ISSUE THREAD

**Issue by sunzhe09** [yangxy/PASD#33]
can you help me？

**Comment by yangxy** [comment]
We simply generate the captions using BLIP-2, Coca, etc.

**Comment by sacred178953** [comment]
> We simply generate the captions using BLIP-2, Coca, etc.

But after I checked the training script and dataset.py, I found there is no graphical module such as blip-2, so which part of the code is generated in the caption

**Comment by yangxy** [comment]
> > We simply generate the captions using BLIP-2, Coca, etc.
> 
> But after I checked the training script and dataset.py, I found there is no graphical module such as blip-2, so which part of the code is generated in the caption

You should generate the captions offline.

**Comment by sunzhe09** [comment]
你好，非常感谢你分享在huggingface上的数据集，可以进一步分享一下图片对应的caption吗？
