### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by ZH3nGsQ** [yangxy/PASD#43]
when I download pre-trained models pasd_light and put them into runs/. And I download SD1.5 models v1-5-pruned-emaonly.ckpt and put them into checkpoints/stable-diffusion-v1-5. I run **python test_pasd.py --use_pasd_light** there is an error : 
**OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory checkpoints/stable-diffusion-v1-5.**
Am I missing something that needs to be downloaded?

**Comment by yangxy** [comment]
we don't use the .ckpt file. Please ```git clone``` the whole SD1.5 model from huggingface including all the subfolders and configs.
