### ISSUE TITLE
How to train PASD on DIV2K_train_HR?

### ISSUE THREAD

**Issue by ZH3nGsQ** [yangxy/PASD#47]
I want to train PASD on DIV2K_train_HR dataset. But I don't know how to change the code in `webdatasets.py`. Do I only need to change `wds_urls` into my dataset path? I already make my dataset a 'tar' file.

**Comment by yangxy** [comment]
It's ok to pass a local .tar path to webdataset.

**Comment by ZH3nGsQ** [comment]
> It's ok to pass a local .tar path to webdataset.
Thanks for reply! But when I change the `wds_urls`  into `wds_urls = "datasets/DIV2K_train_HR.tar"`.
This error occured.
I just changed the code in` webdatasets.py` : line 256.

![image](https://github.com/yangxy/PASD/assets/163538949/5cfcf4c4-7c3c-469b-ab18-4f7a2e788c30)

**Comment by ZH3nGsQ** [comment]
> > > 将本地 .tar 路径传递给 webdataset 是可以的。
> > 
> > 
> > 谢谢回复！但是当我将 改为 时`wds_urls` ，`wds_urls = "datasets/DIV2K_train_HR.tar"`出现 了这个错误。 我刚刚更改了 中的代码` webdatasets.py`：第 256 行。
> > ![图像](https://private-user-images.githubusercontent.com/163538949/337564080-5cfcf4c4-7c3c-469b-ab18-4f7a2e788c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA3NTQsIm5iZiI6MTcyMjkzMDQ1NCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzM3NTY0MDgwLTVjZmNmNGM0LTdjM2MtNDY5Yi1hYjE4LTRmN2EyZTc4OGMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTlmMzlmNDJhYzU4ZWU0MDYxMDEyMTRkY2IzNjA3NTlkYmEwYmU1ZjYzMzRkMmRiM2IyYzI1MWZhYWE1MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PIQ4mzUtaThiNI6oeKypGbvL5atqKWthLh8e1scEpfc)
> 
> Hello.Do you solve the problem?I also have the same problem.
可以使用**localdataset.py**文件，将**pngtxt_dir**改为你本地的数据集的路径，然后把train_pasd.py文件中的762行修改为我这样：
![image](https://github.com/user-attachments/assets/59ec05cd-bd9f-46a1-a976-c5e7e743b90f)
应该就能用自己的数据集进行训练了。

**Comment by wengzp1** [comment]
> > > > 将本地 .tar 路径传递给 webdataset 是可以的。
> > > 
> > > 
> > > 谢谢回复！但是当我将 改为 时`wds_urls` ，`wds_urls = "datasets/DIV2K_train_HR.tar"`出现 了这个错误。 我刚刚更改了 中的代码` webdatasets.py`：第 256 行。
> > > ![图像](https://private-user-images.githubusercontent.com/163538949/337564080-5cfcf4c4-7c3c-469b-ab18-4f7a2e788c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA3NTQsIm5iZiI6MTcyMjkzMDQ1NCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzM3NTY0MDgwLTVjZmNmNGM0LTdjM2MtNDY5Yi1hYjE4LTRmN2EyZTc4OGMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTlmMzlmNDJhYzU4ZWU0MDYxMDEyMTRkY2IzNjA3NTlkYmEwYmU1ZjYzMzRkMmRiM2IyYzI1MWZhYWE1MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PIQ4mzUtaThiNI6oeKypGbvL5atqKWthLh8e1scEpfc)
> > 
> > 
> > Hello.Do you solve the problem?I also have the same problem.
> > 可以使用**localdataset.py**文件，将**pngtxt_dir**改为你本地的数据集的路径，然后把train_pasd.py文件中的762行修改为我这样：
> > ![image](https://private-user-images.githubusercontent.com/163538949/355366864-59ec05cd-bd9f-46a1-a976-c5e7e743b90f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzI1MzYsIm5iZiI6MTcyMjkzMjIzNiwicGF0aCI6Ii8xNjM1Mzg5NDkvMzU1MzY2ODY0LTU5ZWMwNWNkLWJkOWYtNDZhMS1hOTc2LWM1ZTdlNzQzYjkwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODE3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ0MTViZDU3ODNjMTNlMWMwOTBlMjY0N2MyMGRiOTdkMTViNzE2NTAxOTE2ODE4NzViZWVmY2ExZjAxN2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-s0H8AR41aj2XHLlikO7sgW_SlMpYKWYg6qEeCMEHA)
> > 应该就能用自己的数据集进行训练了。

你好，当我使用您的方法后我还是遇到一样的问题，请问需要修改train_pasd.sh文件吗，我的报错是
<img width="1016" alt="1722934628126" src="https://github.com/user-attachments/assets/0b69baba-87de-4e64-ac6d-1c18c7c8a174">

**Comment by ZH3nGsQ** [comment]
> > > > > 将本地 .tar 路径传递给 webdataset 是可以的。
> > > > 
> > > > 
> > > > 谢谢回复！但是当我将 改为 时`wds_urls` ，`wds_urls = "datasets/DIV2K_train_HR.tar"`出现 了这个错误。 我刚刚更改了 中的代码` webdatasets.py`：第 256 行。
> > > > ![图像](https://private-user-images.githubusercontent.com/163538949/337564080-5cfcf4c4-7c3c-469b-ab18-4f7a2e788c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA3NTQsIm5iZiI6MTcyMjkzMDQ1NCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzM3NTY0MDgwLTVjZmNmNGM0LTdjM2MtNDY5Yi1hYjE4LTRmN2EyZTc4OGMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTlmMzlmNDJhYzU4ZWU0MDYxMDEyMTRkY2IzNjA3NTlkYmEwYmU1ZjYzMzRkMmRiM2IyYzI1MWZhYWE1MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PIQ4mzUtaThiNI6oeKypGbvL5atqKWthLh8e1scEpfc)
> > > 
> > > 
> > > Hello.Do you solve the problem?I also have the same problem.
> > > 可以使用**localdataset.py**文件，将**pngtxt_dir**改为你本地的数据集的路径，然后把train_pasd.py文件中的762行修改为我这样：
> > > ![image](https://private-user-images.githubusercontent.com/163538949/355366864-59ec05cd-bd9f-46a1-a976-c5e7e743b90f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzI1MzYsIm5iZiI6MTcyMjkzMjIzNiwicGF0aCI6Ii8xNjM1Mzg5NDkvMzU1MzY2ODY0LTU5ZWMwNWNkLWJkOWYtNDZhMS1hOTc2LWM1ZTdlNzQzYjkwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODE3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ0MTViZDU3ODNjMTNlMWMwOTBlMjY0N2MyMGRiOTdkMTViNzE2NTAxOTE2ODE4NzViZWVmY2ExZjAxN2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-s0H8AR41aj2XHLlikO7sgW_SlMpYKWYg6qEeCMEHA)
> > > 应该就能用自己的数据集进行训练了。
> 
> 你好，当我使用您的方法后我还是遇到一样的问题，请问需要修改train_pasd.sh文件吗，我的报错是 <img alt="1722934628126" width="1016" src="https://private-user-images.githubusercontent.com/121023220/355383395-0b69baba-87de-4e64-ac6d-1c18c7c8a174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzU1NjAsIm5iZiI6MTcyMjkzNTI2MCwicGF0aCI6Ii8xMjEwMjMyMjAvMzU1MzgzMzk1LTBiNjliYWJhLTg3ZGUtNGU2NC1hYzZkLTFjMThjN2M4YTE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTA3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2I1ZWFlZGY3NmExMWU0NzgzZWFlMDk2NjA1ODM1MmQ3YjM5NzJkYjFjMzc0OTYwZjIwYTcwMzYyM2JiNGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PcI9q3G1PnSXWz4c4VCa5eNXVgLxEO9Qz-6ldqqHl90">

把train_pasd.py文件中的第580行代码解注释就行了

**Comment by wengzp1** [comment]
> > > > > > 将本地 .tar 路径传递给 webdataset 是可以的。
> > > > > 
> > > > > 
> > > > > 谢谢回复！但是当我改为时`wds_urls`，`wds_urls = "datasets/DIV2K_train_HR.tar"`出现了这个错误。我刚刚更改了中的代码` webdatasets.py`：第256行。
> > > > > ![图像](https://private-user-images.githubusercontent.com/163538949/337564080-5cfcf4c4-7c3c-469b-ab18-4f7a2e788c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA3NTQsIm5iZiI6MTcyMjkzMDQ1NCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzM3NTY0MDgwLTVjZmNmNGM0LTdjM2MtNDY5Yi1hYjE4LTRmN2EyZTc4OGMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTlmMzlmNDJhYzU4ZWU0MDYxMDEyMTRkY2IzNjA3NTlkYmEwYmU1ZjYzMzRkMmRiM2IyYzI1MWZhYWE1MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PIQ4mzUtaThiNI6oeKypGbvL5atqKWthLh8e1scEpfc)
> > > > 
> > > > 
> > > > 你好，问题解决了吗？我也有同样的问题。
> > > > 可以使用**localdataset.py**文件，将**pngtxt_dir**改为你本地的数据集的路径，然后把train_pasd.py文件中的762行修改为我这样：
> > > > 应该可以用自己的数据集进行训练了。
> > > > ![图像](https://private-user-images.githubusercontent.com/163538949/355366864-59ec05cd-bd9f-46a1-a976-c5e7e743b90f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzI1MzYsIm5iZiI6MTcyMjkzMjIzNiwicGF0aCI6Ii8xNjM1Mzg5NDkvMzU1MzY2ODY0LTU5ZWMwNWNkLWJkOWYtNDZhMS1hOTc2LWM1ZTdlNzQzYjkwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODE3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ0MTViZDU3ODNjMTNlMWMwOTBlMjY0N2MyMGRiOTdkMTViNzE2NTAxOTE2ODE4NzViZWVmY2ExZjAxN2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-s0H8AR41aj2XHLlikO7sgW_SlMpYKWYg6qEeCMEHA)
> > 
> > 
> > 您好，当我使用您的方法后我仍然遇到同样的问题，请问需要修改train_pasd.sh文件吗，我的报错是<img alt="1722934628126" width="1016" src="https://private-user-images.githubusercontent.com/121023220/355383395-0b69baba-87de-4e64-ac6d-1c18c7c8a174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzU1NjAsIm5iZiI6MTcyMjkzNTI2MCwicGF0aCI6Ii8xMjEwMjMyMjAvMzU1MzgzMzk1LTBiNjliYWJhLTg3ZGUtNGU2NC1hYzZkLTFjMThjN2M4YTE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTA3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2I1ZWFlZGY3NmExMWU0NzgzZWFlMDk2NjA1ODM1MmQ3YjM5NzJkYjFjMzc0OTYwZjIwYTcwMzYyM2JiNGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PcI9q3G1PnSXWz4c4VCa5eNXVgLxEO9Qz-6ldqqHl90">
> 
> 把train_pasd.py文件中的第580行代码解注释就行了，代码如下： accelerator = Accelerator( gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_ precision=args.mixed_ precision, log_with=args.report_to, project_dir=logging_dir, project_config=accelerator_project_config, )

好的好的，非常感谢！
