### ISSUE TITLE
Missing Comparison with SUPIR [CVPR 24]

### ISSUE THREAD

**Issue by lyf1212** [yangxy/PASD#52]
Thank you for your wonderful work! I notice that you don't provide a comparison with SUPIR [CVPR24][^1], but your work utilize the base backbone of ControlNet and SUPIR also, and you two works both modify the mid-connection of ControlNet, in your work is "PACD" and in SUPIR is "ZeroSFT block", so I am really wonder more quantitative comparison between your method and SUPIR if it convenient for your teams.

[^1]: https://github.com/Fanghua-Yu/SUPIR

**Comment by yangxy** [comment]
PASD predates SUPIR. Please refer to the SUPIR's paper for the comparison results.

**Comment by lyf1212** [comment]
Sorry for my careless ignorance. Thank you for your reply and this work!
