### ISSUE TITLE
Noise Scheduler and Conditioning Scale

### ISSUE THREAD

**Issue by SafetyLucas** [yangxy/PASD#56]
I've been having some great results with super resolution upscales but I'm confused about where to set the adjustable noise scheduler alpha bar value. I can't find any argument for it. Also, what does the conditioning scale in the Gradio demo do? Finally, does the CFG scale matter if there is no text prompt?

**Comment by yangxy** [comment]
1. As for ANS, please refer to the following content in section 4.2 of the main paper:

`In practice, we choose $\bar{\alpha}_a$ from the values of $\bar{\alpha}_n$, where $n\in\{1,2...N\}$, for convenience. In all of our following experiments, we empirically set $n=900$, \ie, $\bar{\alpha}_{900}=0.1189$, to achieve a good balance between fidelity and perception quality.`

The detailed implementation can be found at:
https://github.com/yangxy/PASD/blob/13d41a215fc22a6ebf192c843d06e5b74c0e5dc4/pipelines/pipeline_pasd.py#L729-L731

2. `Conditioning scale` is used to control the strength of ControlNet.

3. Yes, it still matters.

**Comment by SafetyLucas** [comment]
Thank you. Perhaps this should be a separate issue, but I notice a huge difference in generation when xformers are enabled. The gradio_pasd demo doesn't natively enable xformers from what I could tell but the test_pasd code does. Given the same tiling scales, seed, prompt, etc. without xformers, my upscales are very detailed and sharp, though somewhat unrealistic at close levels (eyelashes go missing, teeth have some strange artifacts, pupils aren't round). With xformers, as in the test_pasd file, my generations are significantly softer at close levels, though somewhat more coherent (intact eyelashes, more natural looking teeth, rounder pupils). Further, generating with xformers takes approximately 1/4 the time of generating without it on my system. This seems like an extreme optimization compared to typical SD image generation. Can you provide any further details about how xformers influences this process?
