### ISSUE TITLE
Colorization model 

### ISSUE THREAD

**Issue by Hznnn** [yangxy/PASD#60]
When I try to colorize the image using the following command:
 ```python3 test_pasd.py --pasd_model_path runs/pasd_light_color/checkpoint-180000 --use_pasd_light --image_path /samples/000080x2.png --output_dir output --upscale 1 --conditioning_scale 0.7 --process_size 256 --control_type grayscale```.
Could you please advise how to modify the command or the parameters to achieve the correct result?

![image](https://github.com/user-attachments/assets/4f59dbae-96a1-4a86-b479-23362812fe1e)

**Comment by BinYCn** [comment]
I had this problem too, have you solved it yet?

**Comment by ALONGNEU** [comment]
> I had this problem too, have you solved it yet?

+1
