### ISSUE TITLE
Support for FLUX?

### ISSUE THREAD

**Issue by AIisCool** [yangxy/PASD#61]
The preview for PASD-SDXL looks amazing! Not sure if it'd be any better, but could support be added for FLUX?

https://huggingface.co/black-forest-labs

Thank you!

**Comment by yangxy** [comment]
Thanks for your suggestion. Unfortunately, I plan to close this project and move forward. I will not update it anymore.Sorry about that.

**Comment by AIisCool** [comment]
> Thanks for your suggestion. Unfortunately, I plan to close this project and move forward. I will not update it anymore.Sorry about that.

Ok, thank you for all your work!
