### ISSUE TITLE
why inference slow in A100 ?

### ISSUE THREAD

**Issue by kelisiya** [yangxy/PASD#9]
when I inference 1024*1024 image , `[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: Done in 12.476s, max VRAM alloc 5802.607 MB`
But I want to use more gpu and fast than now , how to solve it ? 
And inference once some model offload in gpu

**Comment by cswry** [comment]
> when I inference 1024*1024 image , `[Tiled VAE]: the input size is tiny and unnecessary to tile. [Tiled VAE]: Done in 12.476s, max VRAM alloc 5802.607 MB` But I want to use more gpu and fast than now , how to solve it ? And inference once some model offload in gpu

12.476s is not slow for a stable-diffusion based method. You can try to test the same thing in StableSR or DiffBIR.
